name: fryse_page_name
description: Your new Fryse page

theme: default

# Set to true if you want to generate urls like /posts/your-new-fryse-blog instead of /posts/your-new-fryse-blog.html
clean_urls: false

files:
  - from: css
    to: assets/css
  - from: js
    to: assets/js
  - from: images
    to: assets/img
